### ISSUE TITLE
Session lost login not shown and user lose data

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu-standard#149]
When I'm working in Sulu and lost the Session, Sulu don't tell me I must login again.
Currently ajax request are then redirect to login page.

We should check if the request is Ajax then don't redirect just send an 403 Forbidden with a specific Code. 

When the frontend get this specific 403 with this code, it should show an overlay to login over ajax. This overlay will be closed and then he can continue edit the content and can successfully save the content.

So the user can't lose data because of a lost session.

**Comment by danrot** [comment]
https://github.com/sulu-io/sulu/issues/1536 is basically the same issue, but in the correct repository, so I am going to close this one as duplicate.

**Comment by joemoe** [comment]
Yay. got it in the right repository. #bigwin :)

**Comment by danrot** [comment]
#protip: it's almost always sulu-io/sulu ;)
