### ISSUE TITLE
503 Service unavailable 

### ISSUE THREAD

**Issue by chirimoya** [sulu-io/sulu-standard#183]
PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity "...vendor/sulu/security-bundle/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/User.orm.xml" in vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 707

**Comment by nserrar** [comment]
I'm having this bug in our dev server lately, it shows randomly, but not in prod. Nobody seems to have a solution for this, but you talking about it being fixed but how? changing vendor to 
XmlDriver.php Line 736
$xmlData = file_get_contents($file);
$xmlElement = simplexml_load_string($xmlData); 

is not really an option, reinstalling libxml2 or updating didn't work neither.

Thanks for any input that may help.

**Comment by danrot** [comment]
The workaround from https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1062#issuecomment-29473883 worked for us.

**Comment by nserrar** [comment]
@danrot I saw this in that topic but i found it odd that we had to use memcache to fix this bug, if we don't have this in prod that means the bug is related to some configuration in dev only or something broke in our dev server.

**Comment by danrot** [comment]
This bug only appeared on one of our servers, on a different phyiscal one (but as far as we could evaluate with the same configuration and libs) it worked without any problems. We didn't investigate this further, since the workaround worked for us, and caching these entities should also enhance performance.

Sry that I can't help you on this issue...

**Comment by nserrar** [comment]
I give up too, since this workaround fix it ,  i just wanted to understand what caused it at first maybe it hides some other serious problem coming up later.. only time will tell us, thank you.
