### ISSUE TITLE
Exclude not implemented templates for workspace / theme

### ISSUE THREAD

**Issue by chirimoya** [sulu-io/sulu-standard#202]

**Comment by danrot** [comment]
Please remember that the `<excluded>` tag from the XSD for the webspace configurations have to be removed as well. But be aware that this will be a BC-Break.

**Comment by danrot** [comment]
Just had a thought about that, and I am not sure how this should work when we have the theme on the portal. This would mean that we are only allowed to show the templates in the UI which are implemented in all the themes in this webspace, or am I missing something?
