### ISSUE TITLE
Error thrown when user localization not found in ParentChildAnyFindern

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu-standard#220]
It can be that there exists no nodes in a localization then the user can't access the content.
Its in ParentChildAnyFinder at findAvailableLocalization. This function returns then null and error is thrown in getAvailableLocalization at `return $resultLocalization->getLocalization();`

**Comment by danrot** [comment]
Duplicate created at https://github.com/sulu-io/sulu/issues/957

Going to close this one, because the other is in the correct repository.
