### ISSUE TITLE
Server response has content-type:'text/html' instead of 'application/json'

### ISSUE THREAD

**Issue by turbo-ele** [sulu-io/sulu-standard#318]
On my server i get the following response-headers (not working):

```
Connection:close
Content-Type:text/html
Date:Mon, 13 Oct 2014 13:16:57 GMT
Server:Apache/2.2.22
Transfer-Encoding:chunked
X-Powered-By:PHP/5.5.14
```

This is what i have locally (working):

```
Cache-Control:no-cache
Connection:Keep-Alive
Content-Type:application/json
Date:Mon, 13 Oct 2014 09:59:52 GMT
Keep-Alive:timeout=5, max=77
Server:Apache/2.2.26 (Unix) DAV/2 PHP/5.5.17 mod_ssl/2.2.26 OpenSSL/0.9.8za
```

This results in an error when trying to interpret a JSON object.

**Comment by neoenxto** [comment]
When a PHP file has blank spaces before or after tags start or end script (<?php ?>), the server returns the JSON result with a header "Content-Type: text / html" instead of the set in the code, as could be "Content-Type: application / json, charset = utf-8".


Cuando un archivo PHP cuenta con espacios en blanco antes o después de las etiquetas de inicio ó fin del script (<?php ?>) , el servidor muestra el resultado JSON con una cabecera "Content-Type: text/html" en lugar de la configurada en el código, como podría ser "Content-Type: application/json, charset=utf-8".

**Comment by breezyx28** [comment]
> When a PHP file has blank spaces before or after tags start or end script (), the server returns the JSON result with a header "Content-Type: text / html" instead of the set in the code, as could be "Content-Type: application / json, charset = utf-8".
> 
> Cuando un archivo PHP cuenta con espacios en blanco antes o después de las etiquetas de inicio ó fin del script () , el servidor muestra el resultado JSON con una cabecera "Content-Type: text/html" en lugar de la configurada en el código, como podría ser "Content-Type: application/json, charset=utf-8".

ooooooooooh snap it works for me ..... this got me depressed for so long

**Comment by LwtCompany** [comment]
> > Когда в файле PHP есть пробелы до или после тегов start или end script (), сервер возвращает результат JSON с заголовком «Content-Type: text / html» вместо набора в коде, как может быть «Content- Тип: application / json, charset = utf-8 ".
> > Cuando un archive PHP cuenta con espacios en blanco antes or después de las etiquetas de inicio - fin del script (), el servidor muestra el resultado JSON con una cabecera "Content-Type: text / html" en lugar de la configurada en el código , como podría ser "Content-Type: application / json, charset = utf-8".
> 
> оооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооооо работает для меня ..... это меня так долго подавляло

Как исправил свой код пожалуста напиши подробнее
