### ISSUE TITLE
Title of/before button to add Blocks with minOccurs=0

### ISSUE THREAD

**Issue by rs2487** [sulu-io/sulu-standard#324]
If a block has minOccurs 0 there isn't any info at the "add Button" which tells me which kind of block i can add "here".

**Comment by wachterjohannes** [comment]
@danrot i think @rs2487 will say that we dont show the name of the block in the ui perhaps we should discuss this with @berdhep where to place this title

**Comment by danrot** [comment]
I think you mean @berndhep ;-)

**Comment by berndhep** [comment]
Let's discuss this in our weekly.
