### ISSUE TITLE
SmartContent: Shadow Pages children of shadowed page

### ISSUE THREAD

**Issue by wachterjohannes** [sulu-io/sulu-standard#333]
Following scenario:

* de:
  * page
     * subpage1
     * subpage2
* de_at:
  * page (shadow to `de`)
     * subpage1 (shadow to `de`)
     * subpage2 (shadow to `de`)
     * individual subpage (only in de_at)

 when i now gotto: `/de/page` i get in smart content:

* subpage1
* subpage2

and on `de_at/page` i get the same. But i would expect that `individual page` appears to! is this correct? if yes there is a bug ... if no this is a feature (=

**Comment by chirimoya** [comment]
works as expected
