### ISSUE TITLE
Replace ContentMapperRequest

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu-standard#353]
The `ContentMapperRequest` introduced in  just groups all of the parameters of the `ContentMapper`'s `save`-method. I also think that the parameters passed to the `save`-method should be reduced, but this can't be the solution. Maybe we can group some other parameters in a more sensible way?

The `ContentMapperRequest` was introduced in https://github.com/sulu-cmf/sulu/pull/277

**Comment by danrot** [comment]
Would probably be solved as part of https://github.com/sulu-cmf/sulu/issues/685

**Comment by dantleech** [comment]
surely
