### ISSUE TITLE
Current compass version generates sourcemap by default

### ISSUE THREAD

**Issue by turbo-ele** [sulu-io/sulu-standard#373]
In current Sass / Compass installations (compass > 1.0) sourcemaps are generated by default. 

Either we start adding sourcemap files to the repositories (and everyone should switch to a current version of compass/sass), OR we disable the sourcemap generation in the grunt config:
```
compass: {
            dev: {
                options: {
                    sourcemap: false,
...
```

**Comment by wachterjohannes** [comment]
seems not that this was an issue in the last year! i will close this!
