### ISSUE TITLE
app/console is not working because database does not exist

### ISSUE THREAD

**Issue by peric** [sulu-io/sulu-standard#421]
I've tried to setup the project by following the README file, but I cannot continue after ```composer install``` because whatever I'm trying to run with ```app/console```, it breaks because of

```
[Doctrine\DBAL\Exception\ConnectionException]
An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'mowe'
```

So basically, I say ```app/console doctrine:database:create``` and I receive the error from above - does not make sense at all.

My coworker says there is apparently some service that is requesting the database, but it's not aware that database does not exist at this point.

Any ideas what to do here?

**Comment by dantleech** [comment]
Hi, this is a jackalope-doctrine-dbal issue, [a fix will be made available](https://github.com/jackalope/jackalope-doctrine-dbal/pull/242) in the next release.

In the meantime you can manually create the database:

````
$ mysqladmin create mowe -u root
````

or

````
$ mysql
> CREATE DATABASE mowe
````

**Comment by peric** [comment]
Ok, thanks for the quick answer - I'll wait for the new release.

And yes, I already did it manually. Thanks ;)

**Comment by danrot** [comment]
I would leave this issue open for reference, until the new version is released. However, we should remember closing it, as soon as the new release is available :-)

**Comment by danrot** [comment]
AFAIK this bug has already been fixed, so I'll close it.
