### ISSUE TITLE
Country code in the url does not change

### ISSUE THREAD

**Issue by peric** [sulu-io/sulu-standard#422]
In the admin, when you change from one language to the other (for example from "de" to "en"), language changes but the url stays the same (i.e. http://dev-env/admin/#snippet/snippets/de it's shown for both languages).

**Comment by danrot** [comment]
@berndhep What's the desired behaviour here? Should the language of the current content also change when you change the language of the admin interface?

**Comment by berndhep** [comment]
We will discuss a solution for this. Changing the interface language should not affect the language setting of the content IMO. But I understand, that there should be an easy way to switch the default language.

**Comment by danrot** [comment]
@berndhep What should we do about this issue? There is no real solution for this until now, is it?

**Comment by chirimoya** [comment]
Changing the interface language should not affect the language setting of the content.
