### ISSUE TITLE
Wrong Internal Link Title

### ISSUE THREAD

**Issue by leph24** [sulu-io/sulu-standard#423]
When creating an internal link from the main navigation to a subnavigation, the title in the navigation returns the subnavigation title instead keeping the main navigation title

example:
main navigation -> sub navigation
returns to this instead: sub navigation -> sub navigation

Tested in Sulu 0.14.1 and 0.16

**Comment by danrot** [comment]
You are talking about the internal link in the settings tab?

**Comment by leph24** [comment]
yes I do

**Comment by wachterjohannes** [comment]
this title should be used in navigation and internal links!
