### ISSUE TITLE
Adding Images Bug

### ISSUE THREAD

**Issue by leph24** [sulu-io/sulu-standard#430]
After I added images (and don't save) and start adding more images, the images added in the second attempt are not shown. But when I click on "add images" all images are selected. Also those in the second attempt. So I can't reselect them.

If I save before the second attempt to add images it works just fine.

**Comment by leph24** [comment]
After Saving and reloading all selected images are shown, although you couldn't see them before.

**Comment by danrot** [comment]
Related to https://github.com/sulu-io/sulu/issues/894
