### ISSUE TITLE
Editing tags: no changes are visible in front end (data-grid)

### ISSUE THREAD

**Issue by rs2487** [sulu-io/sulu-standard#438]
Editing a tag is workink in backend (the changed tag is saved correctly) but there is no impact on the frontend. The old value of the tag is visible!

**Comment by rs2487** [comment]
Following commit in husky is responsible for the bug:
https://github.com/massiveart/husky/commit/e57a58146e4af9da8a4772c79da10df607c1bbef

In Funktion `renderBodyRow()`
Line 29489: `if (!this.table.rows[record.id]) {`

i think the closing bracket is to late in the code.

**Comment by danrot** [comment]
@michaelzangerle Can you explain this change?

**Comment by michaelzangerle** [comment]
@danrot Sorting of tags works like everywhere else (which should probably be discussed sometime). This means when you sort tags for example ascending then a child tag could be rendered before the parent tag and the nested datagrid view will break. Therefore all parent tags have to be rendered before the specific child tags.

**Comment by danrot** [comment]
As said in this issue in the tags, or anywhere else we are doing inline editing in datagrids. Does this check have to happen in the `renderBodyRow` method? Can't you just put the if around the specific call if you show a nested list?

**Comment by michaelzangerle** [comment]
I did not find any variable/option which would indicate that it is a nested view (just "table") but yes if we would introduce such a variable we could change the condition and handle this case differently.

**Comment by rs2487** [comment]
The issue seems to be fixed, but adding a new row to the datagrid, the POST request always executed two times. So an exceptions is thrown that the entity (tag e.g.) already exists.

**Comment by danrot** [comment]
@rs2487 There is a separate issue for that: https://github.com/sulu-io/sulu/issues/1018
