### ISSUE TITLE
Serverfehler400 on adding dublicated tag

### ISSUE THREAD

**Issue by rs2487** [sulu-io/sulu-standard#439]
On adding a existing tag, i got a "Serverfehler400". It seems that the validator does not work correctly.

**Comment by rs2487** [comment]
The solution is to remove row 49

46            this.sandbox.emit('sulu.labels.error.show',
47                translationKeyForError,
48                'labels.error',
49                ''
50            );

**Comment by danrot** [comment]
Now you get both errors, right? The error message is not "wrong", since the server really returns a 400 for this request. However, we should maybe remove the general server error never the less (although I would keep the handling for 403 errors) /cc @chirimoya @dantleech

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu/issues/1018
