### ISSUE TITLE
Keep Symfony2 Standards for Roles names

### ISSUE THREAD

**Issue by sRmarcos** [sulu-io/sulu-standard#443]
Maybe it is a good idea to keep symfony2 standards in the Role names. The `BaseRole` Entity on the SecurityBundle use `SULU_ROLE_` in the `getIdentifier` and `getRole` function. Using `ROLE_SULU_` would be compatible with Symfony2 and they could be use for the firewall.

**Comment by danrot** [comment]
Didn't know that there is a standard which we need to follow in order to be compatible with the firewall... We will of course change that, if this is the case.

Originally I thought the Sulu roles are easier to recognize if they are prefixed with `SULU_ROLE_`.

**Comment by sRmarcos** [comment]
Duplicate|Waiting: https://github.com/sulu-io/sulu/issues/1159
