### ISSUE TITLE
Navigation Context for Shadow Pages

### ISSUE THREAD

**Issue by sRmarcos** [sulu-io/sulu-standard#445]
When a page is set as shadow, it is not shown in the navigations context unless the user added to a context and save the page before checking and saving the page as a shadow. This could be easily fix by keep the navigation context dropdown active for shadow pages. 

Steps to reproduce:
1. Create a page in any language, give it a name, url, publish it and save it. Now add it to a navigation context and save it again.
2. Use the localization dropdown to create a translation for the page.
3. Without changing a thing, go to settings and select a shadow language and check the shadow page checkbox.
4. Check that the translated page is not show in the navigation menu.

**Comment by wachterjohannes** [comment]
@berndhep what would you say to that fix? technically it would be no problem to solve that issue if we keep the dropdown active!

**Comment by wachterjohannes** [comment]
@sRmarcos @berndhep i have talked to @chirimoya a few days ago about that topic ... the navigation context should be derived from shadowed language!

**Comment by sRmarcos** [comment]
@wachterjohannes Yes, you are definitely right.

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu-standard/issues/445

**Comment by danrot** [comment]
@chirimoya Guess you have linked the wrong number here ;-)

**Comment by danrot** [comment]
I think the issue this is a duplicate of is https://github.com/sulu-io/sulu/issues/1007

**Comment by chirimoya** [comment]
;-) thx
