### ISSUE TITLE
Too large response when accessing permissions tab in crm

### ISSUE THREAD

**Issue by michaelzangerle** [sulu-io/sulu-standard#469]
Sometimes when accessing the permissions tab for a person (CRM) following error is returned.

```GET http://stage.pool-alpin.com/admin/api/users?contactId=21911 net::ERR_INCOMPLETE_CHUNKED_ENCODING```

According to @christianbader the response is to big because the user entity gets serialized completely.

**Comment by oliverpretz** [comment]
nach Trello übernommen

**Comment by danrot** [comment]
@oliverpretz this issue should stay open, since it is also a serious error for us (it is not specific to your project)
