### ISSUE TITLE
Unable to save changes after getting error on datagrid

### ISSUE THREAD

**Issue by rs2487** [sulu-io/sulu-standard#478]
It's not possible to add/edit data in the datagrid after e error was thrown. The bug didn't exist in 0.18.2.

Reproducing:
1.) Enter a tag that already exists - An error occurs
2.) Type in another name for the tag, press enter - nothing more happens

**Comment by danrot** [comment]
Can be solved for now with another click on the add button. Then the red border is removed, and you can add something again.
