### ISSUE TITLE
IE11: Changes in Tab "Berechtigungen" can't be saved

### ISSUE THREAD

**Issue by pjeroen** [sulu-io/sulu-standard#494]
e.g. changing the user's password doesn't enable the save button.

**Comment by chirimoya** [comment]
@marcelmoosbrugger can you have a look?

**Comment by chirimoya** [comment]
@pjeroen which version?

**Comment by pjeroen** [comment]
@chirimoya @marcelmoosbrugger I tested in IE11

**Comment by chirimoya** [comment]
@pjeroen sorry, I did mean which Sulu version? ;-)

**Comment by marcelmoosbrugger** [comment]
@pjeroen @chirimoya works in current develop branch. Tested in IE Edge and IE 10 under Windows 8
