### ISSUE TITLE
Remove deprecated sulu_meta_seo function from default template.

### ISSUE THREAD

**Issue by joemoe** [sulu-io/sulu-standard#504]
I heard the sulu_meta_seo Twig function is deprecated, but it's still in the default template.
We should change that as they seem to be one of our top references.
https://github.com/sulu-io/sulu-standard/blob/develop/src/Client/Bundle/WebsiteBundle/Resources/themes/default/blocks/meta.html.twig

**Comment by danrot** [comment]
Fixed in #493
