### ISSUE TITLE
"No input file specified" error right after install

### ISSUE THREAD

**Issue by ChristopheLecroq** [sulu-io/sulu-standard#506]
Hi,

I'm sorry to post here this kind of problem but like I have scrupulously read the doc and can't understand why I have this 'No input file specified' error.

In NGINX log, I've : 

Unable to open primary script: /var/www/cadomus.org/web/website.php

I've NGINX & PHP-FPM web server on my Archlinux computer and no error during the install of Sulu.

- I've checked permission, file and directory (execute)
- I've re-installed my NginX, so my configuration is standard.

Thank you in advance (any idea are welcome !)

**Comment by danrot** [comment]
Do you use the config file you can find in our documentation: http://docs.sulu.io/en/latest/book/getting-started/vhost.html  ?

**Comment by ChristopheLecroq** [comment]
Hi Daniel, 

Is it a new layout for the doc ? I  don't remember this one... By the way, It's seems similar to me (I can't watch the file right now but I'm pretty sure). I re-installed my computer yesterday and I'll try a new set up after work. 

Thank you very much for your help

**Comment by danrot** [comment]
Yeah, there is a new layout. Just let us know if it works out this time. But I can guarantee you that this error is caused by nginx.

**Comment by ChristopheLecroq** [comment]
It's works (at the first time) !! :) My old configuration was corrupted, I think. Sorry for the trouble and once again thank you !

ps : thankfully to the new documentation, I've understood why the software is called "Sulu" :D
