### ISSUE TITLE
SQL Error accessing Assets

### ISSUE THREAD

**Issue by carltongibson** [sulu-io/sulu-standard#516]
Hi. I'm just getting going so most likely I've set things up wrong but... :)

I've got a clean instal set up following the docs. 

I'm getting a `Doctrine\\DBAL\\Exception\\DriverException` when accessing the Assets panel.

The SQL being generated is this: 

```
"SELECT COUNT(m0_.id) AS sclr0 FROM me_media m0_ ORDER BY m0_.changed DESC"
```

PostgreSQL complains about this: 

```
NOTICE:  identifier "SELECT COUNT(m0_.id) AS sclr0 FROM me_media m0_ ORDER BY m0_.changed DESC" will be truncated to "SELECT COUNT(m0_.id) AS sclr0 FROM me_media m0_ ORDER BY m0_.ch"
ERROR:  syntax error at or near ""SELECT COUNT(m0_.id) AS sclr0 FROM me_media m0_ ORDER BY m0_.changed DESC""
LINE 1: "SELECT COUNT(m0_.id) AS sclr0 FROM me_media m0_ ORDER BY m0...
        ^
Query failed
PostgreSQL said: syntax error at or near ""SELECT COUNT(m0_.id) AS sclr0 FROM me_media m0_ ORDER BY m0_.changed DESC""
```

That's the exact error that's being reported back to PHP. 

This is with Sulu 1.0.12.

**Comment by danrot** [comment]
Is it possible that the error is caused by the fact that you've used the command with the quotes? The quotes are also doubled in the error message, that's why I am asking. And to be honest I am not a postgres sql export, so I don't really know why this query doesn't work...

**Comment by carltongibson** [comment]
Ah — error copy and pasting to report the issue. (Sorry!)

Here's the actual error, when correctly run in Postgres:

```
ERROR:  column "m0_.changed" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...COUNT(m0_.id) AS sclr0 FROM me_media m0_ ORDER BY m0_.change...
                                                             ^
Query failed
PostgreSQL said: column "m0_.changed" must appear in the GROUP BY clause or be used in an aggregate function
```

I'm just getting started here, so I don't know the code base, but it touches the Sulu codebase here: 

```
            "file": "/Users/carlton/Documents/Sulu/sulu-standard/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php", 
            "function": "getSingleResult", 
            "line": 151,
```

This is where things get passed off to Doctrine. 

I'm assuming I've done something wrong since the query being generated leads to the error — but *everything else* seems good — and being new I've no idea. 

On "Everything else": The only other thing I'm seeing is a ...

```
FatalErrorException in ExceptionController.php line 67:
Error: Call to a member function getTheme() on a non-object
```

...when accessing the example website. But I'm assuming I'll work that out momentarily, and it's the _other end_ of the stack, so to speak, so I can't see how it's related. 

Thanks for the help!

**Comment by danrot** [comment]
I am sry about "Everything else", we should really add a better error here... It basically means that there is some error in your xml config file in `app/Resources/webspaces/`.

About the other error it looks to me like this is really a bug only appearing in combination with PostgreSQL... We currently run the tests only against MySQL...

@chirimoya Should we add a travis environment with PostgreSQL or remove that support from the documentation.

@alexander-schranz Is there any reason we are doing this order in this case? Or could it be easily removed?

**Comment by alexander-schranz** [comment]
@danrot yes we can remove the orderBy and orderSort from the count method in the MediaRepository because its not necessary.

**Comment by carltongibson** [comment]
If you let me know what, I'm happy to test changes here — I can't see any reason why Postgres shouldn't _Just Work_

**Comment by alexander-schranz** [comment]
In the MediaRepository:count Method

**From:**
``` php
$this->getIdsQuery($collection, $types, $search, $orderBy, $orderSort, null, null, 'COUNT(media)');
```


**To:**
``` php
$this->getIdsQuery($collection, $types, $search, null, null, null, null, 'COUNT(media)');
```

**Comment by chirimoya** [comment]
@danrot please add PostgreSQL and give it a try

**Comment by carltongibson** [comment]
OK, so progress... 😀

I made the change to `MediaRepository::count` as per @alexander-schranz's instructions.

The request for the main panel is now working. 

*  `/admin.php/admin/api/media?orderBy=media.changed&orderSort=desc&locale=en&fields=id,thumbnails,name,size,title,description&limit=20`

There is though a **second request** — which must be for the Collection List on the left. 

* [500]: /admin.php/admin/api/collections?sortBy=title&page=1&limit=20

Here there's a long SQL statement that ends like this: 

```
LEFT JOIN me_collection_meta m6_ ON m4_.id = m6_.idCollections WHERE (m0_.depth <= ? + ? OR m5_.depth <= ?) AND (m1_.locale = ? OR m2_.id <> ?) ORDER BY m1_.title ASC) dctrn_result ORDER BY title7 ASC LIMIT 20 OFFSET 0
```

See the `?`s that appear? It's like bound parameters haven't been substituted. (Full SQL statement at the bottom)

Postgres complains about this: 

```
ERROR:  syntax error at or near "OR"
LINE 1: ....id = m6_.idCollections WHERE (m0_.depth <= ? + ? OR m5_.dep...
                                                             ^
Query failed
PostgreSQL said: syntax error at or near "OR"
```

... and we get a `Doctrine\DBAL\Exception\DriverException`:

```
An exception occurred while executing 'SELECT DISTINCT id4, ...'
```

It comes from `MediaBundle/Controller/CollectionController.php` in `getTree` calling `iterator_to_array`, which hands off to Doctrine. 



```
---- Full SQL for Failing Requesing ----
SELECT DISTINCT id4, title7 FROM (SELECT m0_.style AS style0, m0_.lft AS lft1, m0_.rgt AS rgt2, m0_.depth AS depth3, m0_.id AS id4, m0_.created AS created5, m0_.changed AS changed6, m1_.title AS title7, m1_.description AS description8, m1_.locale AS locale9, m1_.id AS id10, m2_.title AS title11, m2_.description AS description12, m2_.locale AS locale13, m2_.id AS id14, m3_.name AS name15, m3_.description AS description16, m3_.id AS id17, m4_.style AS style18, m4_.lft AS lft19, m4_.rgt AS rgt20, m4_.depth AS depth21, m4_.id AS id22, m4_.created AS created23, m4_.changed AS changed24, m5_.style AS style25, m5_.lft AS lft26, m5_.rgt AS rgt27, m5_.depth AS depth28, m5_.id AS id29, m5_.created AS created30, m5_.changed AS changed31, m6_.title AS title32, m6_.description AS description33, m6_.locale AS locale34, m6_.id AS id35 FROM me_collections m0_ LEFT JOIN me_collection_meta m1_ ON m0_.id = m1_.idCollections LEFT JOIN me_collection_meta m2_ ON m0_.idCollectionsMetaDefault = m2_.id LEFT JOIN me_collection_types m3_ ON m0_.idCollectionTypes = m3_.id LEFT JOIN me_collections m4_ ON m0_.idCollectionsParent = m4_.id LEFT JOIN me_collections m5_ ON m0_.id = m5_.idCollectionsParent LEFT JOIN me_collection_meta m6_ ON m4_.id = m6_.idCollections WHERE (m0_.depth <= ? + ? OR m5_.depth <= ?) AND (m1_.locale = ? OR m2_.id <> ?) ORDER BY m1_.title ASC) dctrn_result ORDER BY title7 ASC LIMIT 20 OFFSET 0

**Comment by danrot** [comment]
@carltongibson Thank you for your report so far, I just installed postgres on my machine, and will try to get this running. Is probably easier than letting you try out every single step :smile:

**Comment by carltongibson** [comment]
Indeed. 😀

One more piece of info though... I upped the tools a level and was looking at the stack trace again. After the very long SQL statement I get this, which is from `Doctrine\DBAL\Driver\PDOException`:

```
An exception occurred while executing...[LONG SQL STATEMENT] ...with params [0, 0, 1, \"en\", \"en\"]:

SQLSTATE[42725]: Ambiguous function: 7 ERROR:  operator is not unique: unknown + unknown

LINE 1: ...m4_.id = m6_.idCollections WHERE (m0_.depth <= $1 + $2 OR m5...\n                                                             

HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```

I'd to search but if the mentioned casts can be added in `CollectionRepository::findCollectionSet` then (I'm thinking) it may be resolved. 

Let me know if I can do more.

**Comment by carltongibson** [comment]
In the same frame the params array looks like this: 

```
"array",
                {
                  "1": [
                    "string",
                    "0"
                  ],
                  "2": [
                    "string",
                    "0"
                  ],
                  "3": [
                    "string",
                    "1"
                  ],
                  "4": [
                    "string",
                    "en"
                  ],
                  "5": [
                    "string",
                    "en"
                  ]
                }
```

**Comment by danrot** [comment]
I've tracked down the issue, Doctrine is generating a query not suitable for postgres, don't know if it should also be considered a bug there. However, I changed the queries in order to work with postgres again, and added a postgres environment to travis in https://github.com/sulu-io/sulu/pull/1625, let's see if that works.
