### ISSUE TITLE
Default Theme not set-up correctly

### ISSUE THREAD

**Issue by carltongibson** [sulu-io/sulu-standard#518]
Hi. 

This is a _Getting Started_ issue. With Sulu 1.0.12. On a clean install, having followed the guide. 

When accessing the website — just `/` — there's a cryptic error:

```
PHP Fatal error:  Call to a member function getTheme() on a non-object in .../sulu-standard/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Controller/ExceptionController.php on line 67
```

Tracking this down it comes from `Sulu\Component\Webspace/Webspace::getTheme`, which is just a getter for `$this->theme` — which is obviously null here. 

What I can't see is why?

On #516 @danrot [commented](https://github.com/sulu-io/sulu-standard/issues/516#issuecomment-142878871):

> ... It basically means that there is some error in your xml config file in app/Resources/webspaces/.

The relevant section from my XML file there is this: 

```
    <theme>
        <key>default</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">overview</default-template>
        </default-templates>

        <error-templates>
            <error-template default="true">ClientWebsiteBundle:views:error.html.twig</error-template>
            <error-template code="404">ClientWebsiteBundle:views:error404.html.twig</error-template>
        </error-templates>
    </theme>
```

This is just the default that comes from working through the install guide: 

     cp app/Resources/webspaces/sulu.io.xml.dist app/Resources/webspaces/sulu.io.xml

... and so on. 

----

Having got here, at this point I was expecting a basic non-styled set of templates that would at least allow the pages created in the admin to render — but that seems to be missing. 

Is there a bundled theme? If yes, how do I get it to work? If not, what's the minimum needed? And, for the issue, can this be added to the guide?

Thanks for the help!

**Comment by wachterjohannes** [comment]
the problem normally with this exception is that there is no valid webspace ... can you post the full webspace.xml file?

**Comment by carltongibson** [comment]
Hi @wachterjohannes — Thanks for the quick reply! Sure...

```
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.0.xsd">

    <name>sulu.io</name>
    <key>sulu_io</key>

    <localizations>
        <localization language="en" shadow="auto">
            <localization language="en" country="us" shadow="auto"/>
        </localization>
        <localization language="de">
            <localization language="de" country="at"/>
        </localization>
    </localizations>

    <theme>
        <key>default</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">overview</default-template>
        </default-templates>

        <error-templates>
            <error-template default="true">ClientWebsiteBundle:views:error.html.twig</error-template>
            <error-template code="404">ClientWebsiteBundle:views:error404.html.twig</error-template>
        </error-templates>
    </theme>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="de">Hauptnavigation</title>
                    <title lang="en">Mainnavigation</title>
                </meta>
            </context>
            <context key="footer">
                <meta>
                    <title lang="de">Footernavigation</title>
                    <title lang="en">Footernavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>sulu.io</name>
            <key>sulu_io</key>
            <resource-locator>
                <strategy>tree</strategy>
            </resource-locator>

            <localizations>
                <localization language="en" default="true"/>
                <localization language="de"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="en">sulu.us</url>
                        <url language="de">www.sulu.io</url>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>stage.sulu.lo/{localization}</url>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>sulu.lo/{localization}</url>
                        <url language="en">localhost</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>

```

**Comment by carltongibson** [comment]
This is just the copied `app/Resources/webspaces/sulu.io.xml.dist` — not edited. Everything in the admin side is working well.

**Comment by wachterjohannes** [comment]
how do you try to access the website? with `sulu.lo` or different?

**Comment by carltongibson** [comment]
NO. (Grrrr.)

`http://127.0.0.1:8081` — You're going to tell I have to set that right now aren't you?

**Comment by wachterjohannes** [comment]
yeah you have to add this into you urls config (: ip addresses should work to! but if you try localhost:8001 it should work everything (:

**Comment by carltongibson** [comment]
OK — I get the same error for `http://localhost:8081`

**Comment by danrot** [comment]
How do run Sulu? On apache, nginx or using the `app/console server:run` command?

**Comment by carltongibson** [comment]
I've nginx rewriting and then proxying to the PHP development server.

**Comment by danrot** [comment]
I am not sure if I understand correctly... Did you use the file at http://docs.sulu.io/en/latest/book/getting-started/vhost.html#nginx and are you using php-fpm? If not, can you maybe post your nginx configuration?

**Comment by carltongibson** [comment]
I'm not using FastCGI. But I am using nginx to do the rewriting (because it's simpler than writing a router script for the development server). 

Here's the nginx conf, just adapted from the example in the guide:

```
upstream phpdev {
    server 127.0.0.1:4000;
    # server unix:/var/run/php5-fpm.sock; #for PHP-FPM running on UNIX socket
}

server {
    listen 8081;

    server_name sulu.local;
    root /Users/carlton/Documents/Sulu/sulu-standard/web;

    error_log /Users/carlton/var/log/sulu/error.log;
    access_log /Users/carlton/var/log/sulu/access.log;

    # strip app.php/ prefix if it is present
    rewrite ^/app\.php/?(.*)$ /$1 permanent;

    location /admin {
        index admin.php;
        try_files $uri @rewriteadmin;
    }

    location @rewriteadmin {
        rewrite ^(.*)$ /admin.php$1 last;
    }

    location / {
      index website.php;
      try_files $uri @rewritewebsite;
    }

    # expire
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        try_files $uri /website.php/$1;
        access_log off;
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }

    location @rewritewebsite {
        rewrite ^(.*)$ /website.php/$1 last;
    }

    # pass the PHP scripts to FastCGI server from upstream phpfcgi
    location ~ ^/(website|admin|app|app_dev|config)\.php(/|$) {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # http://stackoverflow.com/a/19637196
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;

        proxy_pass   http://phpdev;


#         include fastcgi_params;
#         fastcgi_pass phpdev;
#         fastcgi_buffers 16 16k;
#         fastcgi_buffer_size 32k;
#         fastcgi_split_path_info ^(.+\.php)(/.*)$;
#         fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         fastcgi_param  SYMFONY_ENV dev;
#         fastcgi_param  HTTPS off;
    }
}
```

And then I run PHP like so: 

   .../sulu-standard/web $ php -S 127.0.0.1:4000

**Comment by wachterjohannes** [comment]
hmmm ... i have two suggestions ... 

1. "Host" header will not be set when proxying (could you check this with a `print_r($_SERVER)` in `web/website.php`
2. try to run with `php -S localhost:4000` and change this in your nginx config

**Comment by carltongibson** [comment]
`HTTP_HOST` is set and follows the requested URL as expected. e.g. ` [HTTP_HOST] => localhost:8081` or `[HTTP_HOST] => 127.0.0.1:8081` — this is what the ` proxy_set_header` directive is for. 

No effect changing to `php -S localhost:4000`.

Full `$_SERVER`:

```
Array
(
    [DOCUMENT_ROOT] => /Users/carlton/Documents/Sulu/sulu-standard/web
    [REMOTE_ADDR] => 127.0.0.1
    [REMOTE_PORT] => 54784
    [SERVER_SOFTWARE] => PHP 5.5.27 Development Server
    [SERVER_PROTOCOL] => HTTP/1.0
    [SERVER_NAME] => localhost
    [SERVER_PORT] => 4000
    [REQUEST_URI] => /website.php/
    [REQUEST_METHOD] => GET
    [SCRIPT_NAME] => /website.php
    [SCRIPT_FILENAME] => /Users/carlton/Documents/Sulu/sulu-standard/web/website.php
    [PATH_INFO] => /
    [PHP_SELF] => /website.php/
    [HTTP_X_FORWARDED_FOR] => 127.0.0.1
    [HTTP_X_FORWARDED_PROTOCOL] => http
    [HTTP_HOST] => localhost:8081
    [HTTP_CONNECTION] => close
    [HTTP_DNT] => 1
    [HTTP_COOKIE] => __utma=111872281.1056614540.1392805885.1392805885.1396254906.2; csrftoken=WPfPPdnz8ZVINNTPq4PWO5QnrRZfiQYM
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9
    [HTTP_ACCEPT_LANGUAGE] => en-us
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_CACHE_CONTROL] => max-age=0
    [REQUEST_TIME_FLOAT] => 1443171137.6985
    [REQUEST_TIME] => 1443171137
)
```

**Comment by wachterjohannes** [comment]
hmmis it normal that the host includes the port? i would think there should only stand localhost ...

**Comment by wachterjohannes** [comment]
thats probably the error with sulu here ...

**Comment by carltongibson** [comment]
Well I tried that... 

I put this at the top of `website.php`: 

```
$_SERVER["HTTP_HOST"] = 'localhost';
```

Same `getTheme` error. (And the Admin works...)

Is there anyway of hardcoding the value for theme so I can bypass this for the moment? (Or... where might I insert such a hack?)

**Comment by wachterjohannes** [comment]
the problem is not the null theme ... there is a null webspace here ...

**Comment by wachterjohannes** [comment]
he does not find a webspace for the url here but i have no idea why (: maybe @danrot has another idea

**Comment by wachterjohannes** [comment]
are you in dev mode? because only in dev the URL `localhost` is configured?

**Comment by carltongibson** [comment]
Yes. Of course. 

 I set nginx to set the Host header to `localhost` — without the port — no change. Same error.

**Comment by carltongibson** [comment]
> are you in dev mode? because only in dev the URL localhost is configured?

MAGIC! OK. Thank you. Sorry for the oversight there.

**Comment by wachterjohannes** [comment]
do you know only have changed the Environment or anything else in you nginx config?

**Comment by carltongibson** [comment]
No, literally just the `SYMFONY_ENV` — I feel silly about that. :)

The nginx proxy_pass settings as pasted (including port number as part of the Host header) works as desired.

**Comment by wachterjohannes** [comment]
it would be perfect if you would create a docs entry "How to setup a Development environment" with your configurations (: sounds maybe interesting for a lot of people!

**Comment by wachterjohannes** [comment]
if you want to have "live" support you can join our slack channel (: you only have to put in your contact informations on our website www.sulu.io (scoll down) we will add you soon to the channel!

**Comment by carltongibson** [comment]
@wachterjohannes — Thanks. I opened #519 with my thoughts. I'll follow up with my dev setup in a PR to the docs. I did fill in the form for the Slack channel.

**Comment by wachterjohannes** [comment]
no problem we love to help - if we can (: we will welcome you in our channel soon!

**Comment by ddesplats** [comment]
Hi,
A little precision here : If you are using a server name with a port number as the url of your dev website, you should configure your webpace urls with the server name only. 

For example, My dev website is on http://localhost:8080 so my webspace is configure with the following urls :
\<portals>
        \<portal>
            \<name>sulu-test</name>
            \<key>sulutest</key>
            \<resource-locator>
                \<strategy>tree</strategy>
            \</resource-locator>

            <localizations>
                <localization language="en" default="true"/>
                <localization language="fr"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="fr">localhost</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url language="fr">localhost</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="fr">localhost</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
