### ISSUE TITLE
Cannot init webspaces

### ISSUE THREAD

**Issue by ddesplats** [sulu-io/sulu-standard#530]
Hi,

I'm trying to use sulu but i can't run correctly the command "app/console sulu:build prod" or any other sulu:build command because, when i get to sulu:webspace:init step I have the following error :
[ProxyManager\Exception\FileNotWritableException]
  Could not write to path "C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Sulu\sulu-standard\app\cache\admin\dev\sulu\documents\ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php.561bbc8e14e4f2.77515000": is not writable

I am running this on a local server powered by EasyPHP on Windows 7.

I checked multilpe times the rights of the app\cache\admin\dev\sulu\documents and all users have "total control" hover the path.

Does somebody have any idea ?

Thanks.

**Comment by carltongibson** [comment]
I'm not a Windows expert but, despite what you say, this looks like a permissions issue — all I can say is double check.

**Comment by wachterjohannes** [comment]
@ddesplats i think @carltongibson is right ... maybe clear this folder, set the permissions and try again!

**Comment by ddesplats** [comment]
Already tried this. No way :(

**Comment by ddesplats** [comment]
I finally got throught this :
---> "Program Files (x86)" is very particular with ACL in fu*** windows system an his pretty agnostic on whatever efforts you do to modify ACL under it. 
So I create a new folder under My Documents where I cloned the sulu project and made the install process again. Then I pointed my root directory on it for the virtual host (do not forget to add "Require all grant" under "Allow from all" ). And it works !

Here my virtual host config :
Listen 8080
<VirtualHost *:8080>
    DocumentRoot "C:\Users\Me\Documents\Projets\CMS\Sulu\sulu-standard\web"
    ServerName localhost
    <Directory "C:\Users\Me\Documents\Projets\CMS\Sulu\sulu-standard\web">
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
	Require all granted
        <IfModule mod_expires.c>
            ExpiresActive On
            ExpiresDefault "access plus 1 month"
            ExpiresByType image/gif "access plus 1 month"
            ExpiresByType image/png "access plus 1 month"
            ExpiresByType image/jpeg "access plus 1 month"
            ExpiresByType image/jpg "access plus 1 month"
            ExpiresByType text/javascript "access plus 1 month"
            ExpiresByType text/css "access plus 1 month"
        </IfModule>

        <IfModule mod_deflate.c>
            SetOutputFilter DEFLATE
            SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|png)$ no-gzip dont-vary
            SetEnvIfNoCase Request_URI \.(?:exe|t?gz|zip|bz2|sit|rar)$ no-gzip dont-vary
            SetEnvIfNoCase Request_URI \.pdf$ no-gzip dont-vary

            BrowserMatch ^Mozilla/4 gzip-only-text/html
            BrowserMatch ^Mozilla/4\.0[678] no-gzip
            BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
        </IfModule>
    </Directory>
</VirtualHost>

**Comment by danrot** [comment]
@ddesplats Is your problem fixed with that? If yes, please close this issue :smiley:

**Comment by danrot** [comment]
@ddesplats Reopen in case it is not fixed.
