### ISSUE TITLE
Copy values out of the datagrid

### ISSUE THREAD

**Issue by rs2487** [sulu-io/sulu-standard#531]
It's not possible to highlight a text in the datagrid for copy it to clipboard.

**Comment by danrot** [comment]
We don't want these texts to be markable, because the complete column is clickable to open the edit form.

**Comment by alexander-schranz** [comment]
@danrot if we remove the `user-select: none;` from the css (.husky-table) it would possible and it would not change anything with the clickable behaviour what you think about that?
