### ISSUE TITLE
500 error in $response on first run

### ISSUE THREAD

**Issue by Swader** [sulu-io/sulu-standard#539]
I get a 500 error on first run of the admin URL. Running in a VM.
No error gets logged into server logs. I traced the problem into `$response->send()`, which I `dump`ed out:

<img width="1106" alt="screenshot 2015-10-25 21 01 57" src="https://cloud.githubusercontent.com/assets/1430603/10717540/d28476ec-7b5b-11e5-819e-a91ad257fc98.png">

Visiting `website.php` I get:

> ( ! ) Fatal error: Call to a member function getTheme() on null in /home/vagrant/Code/sulu/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Controller/ExceptionController.php on line 67

Here's my Nginx configuration:

```
server {
    listen 80;
    listen 443 ssl;
    server_name test.app;
    root "/home/vagrant/Code/sulu/web";

    charset utf-8;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/test.app-ssl-error.log error;
    location ~ ^/(website|admin|app)\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/app.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }

    # strip app.php/ prefix if it is present
    rewrite ^/app\.php/?(.*)$ /test.app permanent;

    location /admin {
        index admin.php;
        try_files $uri @rewriteadmin;
    }

    location @rewriteadmin {
        rewrite ^(.*)$ /admin.php/test.app last;
    }

    location / {
      index website.php;
      try_files $uri @rewritewebsite;
    }

    # expire
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        try_files $uri /website.php/test.app;
        access_log off;
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control public;
    }

    location @rewritewebsite {
        rewrite ^(.*)$ /website.php/test.app last;
    }

    location ~ /\.ht {
        deny all;
    }

    ssl_certificate     /etc/nginx/ssl/test.app.crt;
    ssl_certificate_key /etc/nginx/ssl/test.app.key;
```

**Comment by Swader** [comment]
Sorry, the above was the dumped request, not response. Here is the dumped response.

<img width="1077" alt="screenshot 2015-10-25 21 16 48" src="https://cloud.githubusercontent.com/assets/1430603/10717609/c4509c84-7b5d-11e5-9816-7de196aa4409.png">

It would appear the request succeeds in sending the desired value through, it's just that during execution the app fails badly somewhere. Debugging further...

**Comment by Swader** [comment]
Issue went away after following procedure in [this file](http://docs.sulu.io/en/latest/book/getting-started/setup.html).

Maybe remove this ending part from [this page](http://docs.sulu.io/en/latest/book/getting-started/installation.html):

> Now sulu.local/admin - or whatever url your webserver is running on - should load the Sulu backend. More information on how to configure your local webserver: Configure your local Webserver. Congratulations.

... because it won't work unless the above is done first.

**Comment by danrot** [comment]
Issue https://github.com/sulu-io/sulu/issues/1198 might also be related, apart from your argument about the documentation we should also throw a better error message, with the clear warning that there is no correct webspace.

**Comment by afroewis** [comment]
Just want to say that I ran in exactly the same error message on my first install

**Comment by danrot** [comment]
@Swader @afroewis Thanks for your input, I have corrected the documentation, so this should not be an issue anymore.
