### ISSUE TITLE
Post install, create project, and default webspace + theme

### ISSUE THREAD

**Issue by Swader** [sulu-io/sulu-standard#540]
I recommend adding composer post install scripts and directives for create-project support, so that sulu-standard can be spawned with the create-project command, without having to do checkouts of the master branch or manual `composer install` executions.

Further, I would recommend these same post install scripts which ask us the basic params at the end of the installation (database etc) also ask if we want to enable the default webspace, the default admin role, and the default admin user, and whether we want to enable the default theme, along with `app/console sulu:build` activation. Otherwise, more problems like [these](https://github.com/sulu-io/sulu-standard/issues/539) will keep cropping up - there's just too much manual configuration, too many manual steps, for something basic that everyone's going to do anyway.

From a first-run / onboarding perspective, this system is not at all new-user friendly at this point.

**Comment by danrot** [comment]
Thank you for your feedback. There is already a similar issue: https://github.com/sulu-io/sulu/issues/1056, do you agree with the arguments made there?

**Comment by Swader** [comment]
I do, that all sounds exactly what I had in mind, but better phrased.

**Comment by danrot** [comment]
Anything missing there from this issue, or can it be closed as duplicate of the other one?

**Comment by Swader** [comment]
Can be closed.
