### ISSUE TITLE
Warning: Class __PHP_Incomplete_Class has no unserializer

### ISSUE THREAD

**Issue by Swader** [sulu-io/sulu-standard#553]
Note: all the problems below *completely* disappear when front end is in `prod` mode, so this bug is related to #541. However, this is another aspect of it.

---

## Reproduction steps:

Follow procedure [here](http://www.sitepoint.com/?p=118527&preview=1&_ppp=5c599b0d88). Make sure front end is in dev (it will be, if you followed procedure).

---

I keep getting this error on and off (more on than off), but only on the front end. I am completely unable to debug it, don't know where to begin. Google results mostly point to cache clearing but that doesn't help - I have tried restarting the server, clearing APC cache, and clearing cache with console. I have also disabled `boostrap.php.cache` and load via `app/autoload.php`.

Other things I have tried:

1. Commenting out APC caching - no effect
2. Commenting out `$kernel->loadClassCache();` - no effect

The moment of death happens in `$response->send()` but that's too deep down the rabbit hole for me to reliably debug further. It seems to be caused by something in AsseticBundle, but I'm not sure.

---

The one thing I've found that **does** "help" is running `composer run-script post-install-cmd`, which will change the situation into #541. 

---

Screenshot of full debug screen with expanded stack trace:

![warning- class __php_incomplete_class has no](https://cloud.githubusercontent.com/assets/1430603/10980912/ce904672-8404-11e5-8b77-2ba15333adac.png)

**Comment by danrot** [comment]
Please check if the solution suggested in #541 also fixes that.

**Comment by Swader** [comment]
It does. :+1:
