### ISSUE TITLE
Unable to access sections in admin

### ISSUE THREAD

**Issue by gimyo** [sulu-io/sulu-standard#556]
I am unable to access the different sections of the admin on a new install except the section media collections.

If i click on the media collection link i can add media collections but if i click on any other link I can only see the search pane.

Is this a currently known issue or is this the result of a badly configured install?

**Comment by alexander-schranz** [comment]
hi @gimyo,
sounds like an bug which should be fixed (https://github.com/sulu-io/sulu-standard/issues/472).
on which sulu version are you? did you clear your cache (browser + server (`app/console cache:clear`))?

**Comment by gimyo** [comment]
Hi Alexander,

It is actually a fresh install from today with the two hotfixes done by Daniel today so its as up to date of a new install as possible.

Here is the JSON to compare to the other issue but I dont think it is from the same problem

{
   "title":"Sulu",
   "disabled":false,
   "id":"5644c001ca3eb",
   "items":[
      {
         "title":"",
         "disabled":false,
         "id":"5644c001ca3eb",
         "items":[
            {
               "title":"navigation.search",
               "icon":"search",
               "event":"search",
               "eventArguments":"search",
               "disabled":false,
               "id":"5644c001ca3eb"
            },
            {
               "title":"navigation.contacts",
               "icon":"user",
               "disabled":false,
               "id":"5644c001ca3eb",
               "items":[
                  {
                     "title":"navigation.contacts.people",
                     "icon":"users",
                     "action":"contacts\/contacts",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  },
                  {
                     "title":"navigation.contacts.companies",
                     "icon":"building",
                     "action":"contacts\/accounts",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  }
               ]
            },
            {
               "title":"navigation.media",
               "icon":"image",
               "disabled":false,
               "id":"5644c001ca3eb",
               "items":[
                  {
                     "title":"navigation.media.collections",
                     "action":"media\/collections\/root",
                     "disabled":false,
                     "id":"collections-edit",
                     "dataNavigation":{
                        "rootUrl":"\/admin\/api\/collections?sortBy=title",
                        "url":"\/admin\/api\/collections?sortBy=title",
                        "resultKey":"collections",
                        "nameKey":"title",
                        "showAddButton":true,
                        "instanceName":"collections",
                        "translates":{
                           "noData":"",
                           "title":"navigation.media.collections",
                           "addButton":"navigation.media.collections.add",
                           "search":"navigation.media.collections.search"
                        }
                     }
                  }
               ]
            },
            {
               "title":"navigation.settings",
               "icon":"gear",
               "disabled":false,
               "id":"5644c001ca3eb",
               "items":[
                  {
                     "title":"security.roles.title",
                     "icon":"gear",
                     "action":"settings\/roles",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  },
                  {
                     "title":"navigation.settings.categories",
                     "action":"settings\/categories",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  },
                  {
                     "title":"navigation.settings.tags",
                     "icon":"settings",
                     "action":"settings\/tags",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  },
                  {
                     "title":"navigation.settings.cache",
                     "icon":"hdd-o",
                     "action":"settings\/cache",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  }
               ]
            }
         ]
      },
      {
         "title":"navigation.webspaces",
         "disabled":false,
         "id":"5644c001ca3eb",
         "items":[
            {
               "title":"navigation.global-content",
               "icon":"globe",
               "disabled":false,
               "id":"5644c001ca3eb",
               "items":[
                  {
                     "title":"navigation.snippets",
                     "icon":"bullseye",
                     "action":"snippet\/snippets",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  }
               ]
            },
            {
               "title":"sulu.dev",
               "icon":"bullseye",
               "disabled":false,
               "id":"5644c001ca3eb",
               "items":[
                  {
                     "title":"navigation.webspaces.index-page",
                     "action":"content\/contents\/sulu_dev\/edit:index\/details",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  },
                  {
                     "title":"navigation.webspaces.content",
                     "action":"content\/contents\/sulu_dev",
                     "disabled":false,
                     "id":"5644c001ca3eb"
                  }
               ]
            }
         ]
      }
   ]
}

**Comment by alexander-schranz** [comment]
so its an `1.0` version and not a dev or `1.1-RC`?

I did have a look at the changelog currently the fixed bug is only available at 1.1. or dev versions.
Maybe we should make a new 1.0 release with this bugfix @danrot.

More about the bug.
This bug only seems to appear on windows system.
So you could temporarily fix it if this bug not appears on your prod system. Just look at this PR: https://github.com/sulu-io/sulu/pull/1191/files the file you need to edit you find in your project under `vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Navigation/NavigationItem.php` (clear caches after this) at the navigation should now work. If you do a composer update this temporarily fix will be removed you you maybe need to do again but I hope we could move this bugfix into a 1.0 version.

**Comment by danrot** [comment]
I've created a new release, finally fixing that problem for the 1.0 series: https://github.com/sulu-io/sulu-standard/releases/tag/1.0.15
