### ISSUE TITLE
nothing in the admin part

### ISSUE THREAD

**Issue by jelti** [sulu-io/sulu-standard#568]
Hello guys
thank you for the great work
i just installed the sulu project by following the instructions on the guide
the portal can be viewed without problem when i try to go to the admin part. I get a blank page

localhost/web/admin/login

could you help me please?
Thank you in advance

M JELTI

bellow my sulu.io.xml content

```xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.0.xsd">

    <name>mosite.be</name>
    <key>mosite.be</key>

    <localizations>
        <localization language="en" shadow="auto">
            <localization language="en" country="us" shadow="auto"/>
        </localization>
        <localization language="de">
            <localization language="de" country="at"/>
        </localization>
    </localizations>

    <theme>
        <key>default</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">overview</default-template>
        </default-templates>

        <error-templates>
            <error-template default="true">ClientWebsiteBundle:views:error.html.twig</error-template>
            <error-template code="404">ClientWebsiteBundle:views:error404.html.twig</error-template>
        </error-templates>
    </theme>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="de">Hauptnavigation</title>
                    <title lang="en">Mainnavigation</title>
                </meta>
            </context>
            <context key="footer">
                <meta>
                    <title lang="de">Footernavigation</title>
                    <title lang="en">Footernavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>sulu.io</name>
            <key>sulu_io</key>
            <resource-locator>
                <strategy>tree</strategy>
            </resource-locator>

            <localizations>
                <localization language="en" default="true"/>
                <localization language="de"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="en">sulu.us</url>
                        <url language="de">www.sulu.io</url>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>stage.sulu.lo/{localization}</url>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>sulu.lo/{localization}</url>
                        <url language="en">localhost</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
```

**Comment by alexander-schranz** [comment]
hi @jelti 

if there is just a blank page there is something missing. is your environment `dev`?
login should be under http://localhost/admin/login or just http://localhost/admin

please have a look at the log file `app/logs/admin/dev/dev.log` or your apache or nginx log file for `ERRORs` or `CRITICALs`.

also you should configure your portal in the file you post (key, name, urls)

**Comment by wachterjohannes** [comment]
can you post errors from symfony logs, nginx (or any server you use) logs and javascript errors? we discussed a pretty similar problem yesterday in our slack channel there the fix was to restart nginx maybe you should give a try clear your cache and restart the server!

**Comment by danrot** [comment]
The admin should be available at `sulu.lo/admin` or `localhost/admin`, but never at `localhost/web/admin`.

Did you create a virtualhost like described in http://docs.sulu.io/en/latest/book/getting-started/vhost.html?

Alternatively you can also use the `server:run` command from symfony:
```bash
sf server:run --router=app/config/router_admin.php
```

In that case the admin will be available at `127.0.0.1:8000/admin`. As already described in https://github.com/sulu-io/sulu-standard/issues/519 we should maybe also add this information to the documentation. That would make it easier for new users to get Sulu running fast.

**Comment by jelti** [comment]
Thank you guys for your answers.
the thing is that i'm really new in that domain. I just cloned the project and installed in (composer install) and thought that everything is fine. I ve copied the project dir into my web server root and trying to view the web site.
so now, i realized that it will be more complicate:
- i started by modifying the sulu.io.xml and i dont understand really why i need to put urls? if the project is deployed in my local server
- i tried to create a virtual host by using your config file(doc) but nothing is working now

thank you very much for you help
JELTI

**Comment by MM-Psiiirus** [comment]
...well a work-mate had the same problem and couldn't get a custom-domain to work besides sulu.lo ...was pretty strange.

@jelti not sure if u aware of this but Symfony-Project always use the "web"-folder as doc-root so your virtual host should point to "MY-SYMFONY-PROJECT/web" folder not to the project folder.

**Comment by jelti** [comment]
Hi guys.
its ok now.
i've managed to create the virtual host and every thing is ok
i've got also a cache problems due to absent directories in dev (like hateoad ou sulu/document..) . So i created them manually

My main concern now is the performance !
the site is really slow . could you check the request times in the file attached and tell me if its normal?

Thanks in advance

![printscreen](https://cloud.githubusercontent.com/assets/11663571/11594715/dfd9cee0-9aab-11e5-864a-98bf329a54fd.png)

**Comment by wachterjohannes** [comment]
hmm the websocket requests depends on the rendering time of your website. but the rest seems very long for me ... what is your environment windows, mac or linux? nginx or apache?

**Comment by jelti** [comment]
hello,
i'm using windows 8 with apache (xamp)
thanks

**Comment by wachterjohannes** [comment]
@sabinebaer has experiences with windows systems and sulu maybe she can help you!

**Comment by MM-Psiiirus** [comment]
damn that looks strange....can you post your vhost config? 
Did you check if this is maybe a strange routing problem?

**Comment by sabinebaer** [comment]
@jelti The loading times on Windows/XAMP can be decreased noticeable by changing some settings in php.ini, especially by enabling OPcache. Take a look at http://stackoverflow.com/questions/9854848/windows-7-php-symfony2-terribly-slow#answer-17021255.

**Comment by wachterjohannes** [comment]
@jelti was this the answer?

**Comment by danrot** [comment]
Since we haven't heard anything for some time now, I close the issue, please reopen if the problem still occurs.

**Comment by doctorx32** [comment]
Try to run `php bin/console sulu:translate:export`
