### ISSUE TITLE
Directory separator

### ISSUE THREAD

**Issue by stefann-sasori** [sulu-io/sulu-standard#571]
Hello
Sulu 1.1.1
On windows, I randomly faced an issue while displaying in the BEO my page list.

I got this error:
ksort() expects parameter 1 to be array, null given on line 269 
in vendor/sulu/sulu/src/Sulu/Component/Content/Repository/ContentRepository.php at line 273  
I noticed in the target method that the directory separator '/' is hardcoded but on windows directory separator is '\';
What i did as a temporary fix was to insert on line 251 =>
```php
  $path = str_replace('\\', '/', $path);
```
Thanks to the team for this awesome project

**Comment by danrot** [comment]
First of all thank your for giving us feedback :-)

That sounds like an issue that is already addressed in https://github.com/sulu-io/sulu/pull/1858, although I am not really happy with this solution... /cc @wachterjohannes

**Comment by stefann-sasori** [comment]
Yes it's the same thing. So what do you suggest to do now ?

**Comment by wachterjohannes** [comment]
we will fix it there!

**Comment by danrot** [comment]
We are using `dirname` at some place it's not appropriate, that's the actual cause, and that's also where it should be fixed.

**Comment by wachterjohannes** [comment]
i have search for it and we only use it in the `ContentRepository` that it would be quite easy to fix with explode and join! i think it could be a bit more overhead but i think it is acceptable.

**Comment by danrot** [comment]
if there is a performance overhead I am sure it is negligible, and it does what actually should do, you never know if there are more edge case using dirname.

**Comment by danrot** [comment]
BTW, there is a method in phpcr-utils doing exactly that: https://github.com/phpcr/phpcr-utils/blob/778fc1cdffacb0ee99f52790e656a2acb85b9dfa/src/PHPCR/Util/PathHelper.php#L242

**Comment by stefann-sasori** [comment]
Why not just using DIRECTORY_SEPARATOR constant as @danrot first suggested ?

**Comment by danrot** [comment]
@stefann-sasori I never suggested that, I said that I am not glad about this solution. This is just fixing symptoms, not the problem itself. And if the official PHPCR-Utils offer a method to get the parent path that's definitely the better way than using a method, whose purpose is something different. Will just cause more problems in the future.

**Comment by stefann-sasori** [comment]
Sure
