### ISSUE TITLE
Docs: Document all excerpt fields

### ISSUE THREAD

**Issue by afroewis** [sulu-io/sulu-standard#572]
In the sulu docs, not all of page's excerpt information is documented. For example, if a template developer want to make use of the *"Read more"-Text*(*Text für weiterführenden Link* in german), the only way to get the name of this parameter is to look it up in `Sulu/Bundle/ContentBundle/Content/templates/excerpt.xml` because it's not documented anywhere. 

BTW: I think the "more"-excerpt is a **great** feature! It enables content editors to even use custom "Read more"-Links that suit to the page's content. That's a brilliant idea :smiley_cat: 

Also, is there a way to define additional excerpt info in a template definition? Just being curious.

**Comment by wachterjohannes** [comment]
your totally right we should really document this feature! maybe you want to create a issue in our docs-repository or even a PR (: that would be great!

Its totally easy to override the excerpt template you only have to copy the file from the content-bundle into the `app/Resources/pages` folder and you can change the fields.

Thanks the compliment we try to create great software for great people (:

if you would like to have live support you can contact us over our homepage <http://sulu.io/en> and we will add you to our slack channel. there you can meet more people who uses sulu!

**Comment by afroewis** [comment]
Sure, I'll send a PR to your docs repo as soon as I find some time :-)

**Comment by danrot** [comment]
Recreated the issue in the correct repository: https://github.com/sulu-io/sulu-docs/issues/150
