### ISSUE TITLE
Creating an internal link to the same page causes a loop

### ISSUE THREAD

**Issue by afroewis** [sulu-io/sulu-standard#575]
Hi,

Since Sulu 1.1.1, the page in the admin backend to list our page notes does not work. I noticed that everytime I visit the site, Sulu creates a lot of SQL Queries to the **same page** (the same identifier) before the php process gets killed when reaching it's max_execution_time (therefore I got a 502 from nginx). 

I found out that the said page is a **internal link to itself** (one of our content editors must have set that). Looks like this caused Sulu to get into a Query Loop... Unfortunately this made content management impossible :-(. I can tell you the exact query Sulu executed if you want (but this issue is pretty easy to reproduce). 

Sulu should either disallow an internal link to iteelf for pages or do a check when fetching the pages. 

This was my page structure: 
* Schule (internal link to "Schule")
 * Page 1
 * Page 2
 * ...

After I removed the internal link, everything worked nicely. This caused me a lot of headache :D

**Comment by wachterjohannes** [comment]
fixed in the master and develop branch. hotfix will be released soon!

**Comment by afroewis** [comment]
OK, good job :+1:
