### ISSUE TITLE
cannot clear description on media edit 

### ISSUE THREAD

**Issue by tomsvogel** [sulu-io/sulu-standard#580]
If there is a description, it is not possible to remove the text.

**Comment by wachterjohannes** [comment]
which version do you use?

**Comment by wachterjohannes** [comment]
i thought this should be fixed with https://github.com/sulu-io/sulu/pull/1856/files#diff-3ef8245880b2bf40c121ee75c61700d9R705

**Comment by tomsvogel** [comment]
I use 1.09 but it happens also on sulu demo

**Comment by wachterjohannes** [comment]
the fix was introduced in 1.1.1 and the demo is not up to date what i see! @chiroya should update it! maybe we also have tp release a fix for 1.0 @danrot?

**Comment by danrot** [comment]
We've already promised @tomsvogel to another hotfix for 1.0, so we can backport that of course.
