### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by pascalwacker** [sulu-io/sulu-standard#583]
I just tried to install sulu in a PHP7 Vagrant machine. At the end of the composer installation, when it tries to clear the cache and so on, I got an error `PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /var/www/foobar/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/String.php on line 28`

I think the issue is described here: https://github.com/doctrine/phpcr-odm/issues/678. As I see it, the issue should be eliminated by updating this bundle to `~1.3.0` https://github.com/doctrine/DoctrinePHPCRBundle (you require only version `~1.2.0` https://github.com/sulu-io/sulu/blob/develop/composer.json) unfortunately according to my `composer.lock` file also `dantleech/phpcr-migrations-bundle`, `dantleech/glob-finder` and `phpcr/phpcr-shell` require version `1.2.x`.

**Comment by danrot** [comment]
@chirimoya has already been working on the PHP7 compatibility. Not sure what the current state is though...

**Comment by wachterjohannes** [comment]
which version do you use? @chirimoya is working on this and i think he has finished it  but maybe only in develop. the other version are not compatible with PHP 7. @chirimoya @danrot correct me if i am wrong!

**Comment by wachterjohannes** [comment]
ou (: @danrot you were faster than i (:

**Comment by pascalwacker** [comment]
I have tried with `Sulu 1.1.1` (the standard one from the website http://sulu.io/en/download). I assumed, that it will work with PHP 7 since the "System requirements" state `PHP 5.5 or higher`. In my opinion, it would be nice to have there a warning, that it won't work with PHP 7 (yet).

**Comment by danrot** [comment]
Actually I also wanted to link the PR here: https://github.com/sulu-io/sulu-standard/pull/579

And yeah, you are right, we should add that to the documentation. However, if we release that as a hotfix, it might be available quite soon. /cc @chirimoya

**Comment by jimblizz** [comment]
I'm running PHP 7 on my development VM and have this issue. Does anybody know when PR #579 will be merged? I could really use this for a project i'm starting now.

**Comment by chirimoya** [comment]
@jimblizz we currently have some issues with increased memory consumption using php 5.5 & 5.6 (https://github.com/sulu-io/sulu/pull/1906) ... @wachterjohannes will investigate and we hope we can merge this changes soonish into develop

**Comment by jimblizz** [comment]
Thanks @chirimoya
