### ISSUE TITLE
Install fails with Postgres due to duplicate index

### ISSUE THREAD

**Issue by gzumba** [sulu-io/sulu-standard#584]
Error message is Duplicate table: 7 ERROR:  relation "key_idx" already exists.

The Doctrine Schema Tool tries to build multiple indexes with the same name, which is obviously does not work. SchemaTool can be fixed by eg. prefixing the index name with the name of the table, but obviously that is not a real fix.

**Comment by danrot** [comment]
Sadly we are not Postgres compatible at the moment. @carltongibson already started working on that in https://github.com/sulu-io/sulu/pull/1742, but I haven't heard from him since a while...

**Comment by carltongibson** [comment]
Argh! Been flat out, and then was strike by illness in December. 

The 'key_idx' errors appeared after changes to the search component (IIRC) I'm yet to have time to diagnose. 

I'm currently thinking that, whilst we can work around various Postgres/Doctrine compatibility issues here, we ultimately need to address issues with the way Doctrine generates the underlying SQL for Postgres — the obvious thing is wrong a lot of times (and it shouldn't be the client's responsibility to solve that)

**Comment by danrot** [comment]
So you are basically saying that we should fix doctrine? Sounds like quite some work :smile:

**Comment by carltongibson** [comment]
Indeed

**Comment by gzumba** [comment]
I hacked this to Doctrine just to get the installation through:
Adding a simple line to SchemaTool where the index is created (around line 270):
                    if( is_string($indexName)) $indexName = $class->table['name'].'_'.$indexName;
                    $table->addIndex($indexData['columns'], is_numeric($indexName) ? null : $indexName, (array)$indexData['flags'], isset($indexData['options']) ? $indexData['options'] : array());

However, I don't know what would be a good way to solve this issue for real. Hard to believe this would be a bug in Doctrine...

**Comment by carltongibson** [comment]
> Hard to believe this would be a bug in Doctrine...

Yes. Totally. 

But there are a number of cases on Sulu where it works perfectly with MySQL but not Postgres... 

Having spent some time going through the test failures it seems most issues can be fixed by being more particular... — up to you whether you call that a bug with Doctrine or not.

**Comment by danrot** [comment]
@gzumba Found the issue, will be solved with https://github.com/sulu-io/sulu/pull/1944.
