### ISSUE TITLE
Regex in DocumentInspector allows no "-" in webspace key

### ISSUE THREAD

**Issue by dmetzler1988** [sulu-io/sulu-standard#589]
In the DocumentInspector is this regular expression '/^\/%s\/([\w\.]*?)\/.*$/' which don't allow signs like - (names like icde-website).
Change this?!

**Comment by danrot** [comment]
Doesn't matter if we allow this character, but there has to be done something about this anyway. Currently the build tasks fails with the following message if a "-" is used:

```
[PHPCR\RepositoryException]
          Invalid path /cmf//routes/en
```

Either we allow this character again, or we have to improve the validation of the webspace configuration.

/cc @chirimoya @wachterjohannes @dantleech

**Comment by wachterjohannes** [comment]
i would say we allow that caracter

**Comment by sjoerdmaessen** [comment]
Allowing the character would be helpful.

**Comment by dantleech** [comment]
https://github.com/sulu-io/sulu-standard/issues/589#issuecomment-185636879
