### ISSUE TITLE
Add custom modules in sulu admin

### ISSUE THREAD

**Issue by Doum-Super** [sulu-io/sulu-standard#591]
how to add a new modules in sulu admin ?

**Comment by wachterjohannes** [comment]
hello @Doum-Super we are currently working on a complete tutorial series about this topic. the first blog entry was published last week we will release the second one as soon as possible http://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-1

**Comment by danrot** [comment]
@Doum-Super There is already an issue for that in our documentation repository: https://github.com/sulu-io/sulu-docs/issues/4, follow that if you want to stay up to date.
