### ISSUE TITLE
how to check which key is for what

### ISSUE THREAD

**Issue by dmetzler1988** [sulu-io/sulu-standard#595]
please add a check, that you can distinguish between the key to get it separatly.

as example: 
first key is 'google analytics', second key is 'fb-conversion', third key is 'google analytics rollup'
at the first step i only will get the 'google analytics'- and the 'google analytics rollup'-key.

**Comment by wachterjohannes** [comment]
@dmetzler1988 can you explain that a bit more :)

**Comment by dmetzler1988** [comment]
after check with @wachterjohannes this issue can be closed.
the whole tracking-code is implemented in the response.
