### ISSUE TITLE
snippets imbrication

### ISSUE THREAD

**Issue by Doum-Super** [sulu-io/sulu-standard#596]
I wanted to use a snippet as a reference in another one. 
I systematically get this exception.

Attempted to call method "isShadowLocaleEnabled" on class "Sulu\Bundle\SnippetBundle\Document\SnippetDocument"

I would like to achieve  model association in sulu. Is it possible ? how ?

**Comment by wachterjohannes** [comment]
can you post the related template files here?

**Comment by Doum-Super** [comment]
this is the default snippet which include another snippet:
`<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <meta>
        <title lang="de">Standard</title>
        <title lang="en">Default</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>
            </meta>

            <tag name="sulu.node.name"/>
        </property>

        
        <property name="snippets" type="snippet">
            <meta>
                <title lang="en">Snippets</title>
            </meta>
            <params>
                <param name="snippetType" value="auteur"/>
            </params>
        </property>

    </properties>
</template>
`

and the configuration of template in pages folder:

`<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>overview</key>

    <view>ClientWebsiteBundle:templates:default</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="de">Standard</title>
        <title lang="en">Overview</title>
    </meta>


            <properties>
                <property name="title" type="text_line" mandatory="true">
                    <meta>
                        <title lang="de">Titel</title>
                        <title lang="en">Title</title>
                    </meta>
                    <params>
                        <param name="headline" value="true"/>
                    </params>

                    <tag name="sulu.rlp.part"/>
                </property>

                <property name="url" type="resource_locator" mandatory="true">
                    <meta>
                        <title lang="de">Adresse</title>
                        <title lang="en">Resourcelocator</title>
                    </meta>

                    <tag name="sulu.rlp"/>
                    <tag name="sulu.search.field" role="description"/>
                </property>
                
                <section name="content">
                    <meta>
                        <title lang="en">Content</title>
                    </meta>
                    
                    <properties>
                        <property name="snippets" type="snippet">
                            <meta>
                                <title lang="en">Snippets</title>
                            </meta>
                            <params>
                                <param name="snippetType" value="default"/>
                            </params>
                        </property>
                    </properties>

                </section>
            </properties>
</template>`

**Comment by wachterjohannes** [comment]
@Doum-Super we solved the problem and we will release this soon.
