### ISSUE TITLE
Validation errors breaks page (example template) saving

### ISSUE THREAD

**Issue by ustrugany** [sulu-io/sulu-standard#603]
Tested on latest develop branch. 

Screenshot:
![validation-error-breaks-saving](https://cloud.githubusercontent.com/assets/1469441/12812910/0de76a86-cb35-11e5-9d60-ac3092303b55.png)

Validation erros on phone field causes page save to break, top-left indicator keeps animating without result. In google-chrome network tools there is no any request being made after pressing "Save" button.

**Comment by danrot** [comment]
Looks like this is happening always, not specific to the phone field... Looks like that's a serious bug, I have to have a deeper look at that.
