### ISSUE TITLE
Data Fixtures with Snippets

### ISSUE THREAD

**Issue by Doum-Super** [sulu-io/sulu-standard#610]
How to implement a fixture loader which allows you to load static data into your snippet
repository ?

**Comment by wachterjohannes** [comment]
you have to add a class like this https://github.com/sulu-io/SuluDeveloperBundle/blob/master/DataFixtures/Document/LoadSnippetFixture.php into your bundle folder `DataFixtures/Document` then you can run the build command or the command `sulu:document:fixtures:load` to write the to the database.

**Comment by Doum-Super** [comment]
Ok thanks, it works.

**Comment by wachterjohannes** [comment]
no problem (:
