### ISSUE TITLE
Cannot use is_granted() in Twig

### ISSUE THREAD

**Issue by stefann-sasori** [sulu-io/sulu-standard#614]
Hello Team !
Is there any way to use the sulu authorization system in a twig template ? As it seems like twig function
 {% is_granted('ROLE') %} does not work.

Thanks

**Comment by alexander-schranz** [comment]
sulu roles are prefixed with `SULU` and all symfony roles are i ttink prefixed with `ROLE` so the correct name for the Role e.g. Website will be `ROLE_SULU_Website`. @danrot correct me if I'm wrong

**Comment by danrot** [comment]
@alexander-schranz You should be right :-) @stefann-sasori Would be great if you could close that issue, in case this answers your question.

**Comment by stefann-sasori** [comment]
This is what i'm getting:
![image](https://cloud.githubusercontent.com/assets/11821158/13179136/77cd645a-d71a-11e5-90e2-305d958d08c8.png)

as a result of this

![image](https://cloud.githubusercontent.com/assets/11821158/13179170/9fa5391c-d71a-11e5-8ea0-d65841e1f7f5.png)

I would like to perform something like:

![image](https://cloud.githubusercontent.com/assets/11821158/13179243/ed6f9a84-d71a-11e5-9246-23141676df39.png)

The twig function {% is_granted %} is a  helper used to invoke symfony built in 'authorization_checker' in a twig template context.

My question is: As using "is_granted" throws an exception; is there any twig helper in Sulu that performs authorization check for the current user ?
Is there another 'authorization checker' system in Sulu environment ? How to invoke it in a twig template context if true ?

I hope to have been a bit more explicit.

**Comment by chirimoya** [comment]
@stefann-sasori have you added the `SecurityBundle` to the `WebsiteKernel`. I think else it won't work  anyway.

`app/WebsiteKernel.php`
```
$bundles[] = new Symfony\Bundle\SecurityBundle\SecurityBundle();

**Comment by chrysiel** [comment]
Same problem from my side.

**Comment by stefann-sasori** [comment]
@chirimoya I just added it. It still throws the same exception.

**Comment by danrot** [comment]
@stefann-sasori Just to be sure: Did you also clear the cache? And we have not introduced another method for this. AFAIK this twig method should come with the `SecurityBunde`, so having this bundle registered should be enough.

**Comment by stefann-sasori** [comment]
Yes cleared the cache. Have you ever successfully used this function in a sulu powered application ?

**Comment by alexander-schranz** [comment]
@stefann-sasori for me it works on sulu 1.1. / symfony 2.6. I used it in a project where is use my login registration bundle: https://github.com/alexander-schranz/sulu-website-user-bundle. 

I just add as thomas said:

app/WebsiteKernel.php

```
        $bundles[] = new Symfony\Bundle\SecurityBundle\SecurityBundle();
```

use the is_granted only in ESI uncached controllers:

if you are logged in you can output the roles using this: 
```
{{ dump(app.user.roles) }}
{{ dump(is_granted('ROLE_USER')) }}
```

**Comment by stefann-sasori** [comment]
Yes you can. Sorry I've been very busy these days. Didn't have time to look
this issue. I just tried it works. Maybe the security bundle.

2016-03-10 18:15 GMT+00:00 Thomas Schedler <notifications@github.com>:
