### ISSUE TITLE
Implement SuluContactBundle login form

### ISSUE THREAD

**Issue by chrysiel** [sulu-io/sulu-standard#616]
hi can you help me to include in any template of my website sulu contact login and register form in order to create a member area register and login form just like we did with FosUserBundle.

**Comment by alexander-schranz** [comment]
Hi @chrysiel,

i'm currently developing a bundle for login, registration on a webspace. 
You can give it a try or look at the source code to develop your own. 
https://github.com/alexander-schranz/sulu-website-user-bundle will release 1.0 soon when I got time to test all things. `1.0.0-RC1` can be installed over composer.

**Comment by chrysiel** [comment]
ok thx a lot

2016-02-22 7:53 GMT+00:00 L91 <notifications@github.com>:

**Comment by wachterjohannes** [comment]
@chrysiel hopefully this helps you :) if not please reopen this issue

**Comment by chrysiel** [comment]
@alexander-schranz in which file should i insert this lines :
 <security>
        <system>Website</system>
 </security>

**Comment by alexander-schranz** [comment]
@chrysiel you mean the system? your webspace xml config

**Comment by chrysiel** [comment]
ya i put it but i have this error 

Error: Call to a member function getTheme() on a non-object

**Comment by alexander-schranz** [comment]
the getTheme error comes mostly when your webspace xml miss the current domain you access your website. add the domain as url to the correct environment in your webspace xml. also clear the website cache after it: `app/webconsole cache:clear`

**Comment by chrysiel** [comment]
ok got it thx.
