### ISSUE TITLE
Smart Content not working on develop branch?

### ISSUE THREAD

**Issue by tanerdev** [sulu-io/sulu-standard#629]
Hi Team,

I am trying to implement smart content on a standard installation on the develop branch, 

I am unable to select a data source, also if I select a category or tag it always says "no content found". (I have content a with tags and categories setup)

Is this a known issue or is this feature still in development?

Thanks

**Comment by tanerdev** [comment]
I found this in the documentation,

http://docs.sulu.io/en/latest/cookbook/smart-content-data-provider.html

Giving it a go now....

**Comment by danrot** [comment]
@tanerdev Would be nice if you could give us an explanation here, so that we know what the problem was :-)
